### ISSUE TITLE
Schedules CRUD

### ISSUE THREAD

**Issue by aydreeihn** [osTicket/roadmap#10]
**Feature Summary**

We need to build out CRUD functionality for Schedules as well as their UI.

**Intended Outcome of the feature**

Once completed, we will be able to list, view, update, add and delete Schedules.

**PHP basics that must be included**
It is possible to work on these without having to have the UI.
- [x] Schedule Controller
- [ ] Schedule Model that manipulates Schedule Entries
- [ ] Validation rules
- [ ] Basic test cases

**React basics that must be included**
Note: Schedules was partially built out and will need to be updated to the current structure.
- [ ] Schedules module to list, add, and edit Schedules
- [ ] Schedules Form Mockup

**Questions we need to answer**

**Comment by P4zsvwkWfDT7i3F** [comment]
![Image](https://user-images.githubusercontent.com/106413051/172964699-90653266-97a5-4330-b3cc-848b87910d6f.jpeg)
https://user-images.githubusercontent.com/106413051/172964700-0af9bd2b-3870-4f94-a119-b7dedac9b355.MOV
